predefined-configs:
    contractFlowSteps:
      - 创建者发起审批,NONE,【权限拥有者】
      - 设计部审核及提交明细,USERS
      - 财务相关信息审批,FINANCIAL_STAFF,【财务人员审核】
      - 部门经理审批,ORGANIZATION_HEAD
      - 财务相关核查,FINANCIAL_STAFF,【财务人员审核】

    contractTypes:
      - 燃气水地暖,地暖盘管安装单#采暖设备安装调试单
      - 暗装暖气片,暗装暖气片系统安装单#采暖设备安装调试单
      - 明装暖气片,明装暖气片系统安装单
      - 电地暖安装,电地暖工程项目安装单
      - 空气源热泵,热泵系统隐蔽工程安装派工单（风机盘管）#采暖设备安装调试单
      - 地源热泵流,地源热泵打井和连接管派工单#热泵系统隐蔽工程安装派工单（风机盘管）#采暖设备安装调试单
      - 氟空调,氟系统中央空调安装单
      - 工装项目,工装工程系统安装单

    procedures:
      - 地暖盘管安装单
      - 采暖设备安装调试单
      - 暗装暖气片系统安装单
      - 明装暖气片系统安装单
      - 电地暖工程项目安装单
      - 热泵系统隐蔽工程安装派工单（风机盘管）
      - 地源热泵打井和连接管派工单
      - 氟系统中央空调安装单
      - 工装工程系统安装单
