spring:
  datasource:
    driver-class-config: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.14:3306/ch_db_sys_setting?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: zfbpm
    password: zfbpm@1018

server:
  port: 8085

management:
  security:
    enabled: false
